[package]
name = "RustZmap"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5", features = ["derive"] }
crossbeam-channel = "0.5.15"
etherparse = "0.18.0"
ipnet = "2.11.0"
pnet = "0.35.0"

